### ISSUE TITLE
unique device id's should be hashed on the device before being sent

### ISSUE THREAD

**Issue by thequbit** [hhroc/yellr#10]
To maximize anonymity, we should hash the unique ID on the device before sending it.  This hash should be used int he database.  That way if the database is compromised a direct look-up of unique device ID's can be obtained.

**Comment by Z4P0** [comment]
Nice. I'm all for it

**Comment by thequbit** [comment]
I'm not convinced that we should be using the ENI (or whatever the equivalent is) number in any way in the system.

I say the app generates a random hash at start up, and that is their UUID.  Then, if they want to become a validated user, we can associate to an email address.  This then in the database we can link these.

If the user decides to uninstall or switch devices, they will loose that hash.  If they don't want to "loose what they have submitted" they will need to become a verified user, or generate a new hash that things will be submitted against.

Thoughts?

**Comment by Z4P0** [comment]
I like this approach a lot. Lol sorry I can't give any more constructive feedback on these but it definitely sounds good from my end

**Comment by thequbit** [comment]
To recap, the client will need to randomly generate some kind of 'clientid'.  This should be a UUID to ensure there are no duplicates.  The server will handle creating a new user each time a new UUID is seen.

**Comment by thequbit** [comment]
Closing and opening new ticket for uuid method.
