### ISSUE TITLE
Cannot post a question in spanish

### ISSUE THREAD

**Issue by Z4P0** [hhroc/yellr#106]
I was testing out the create_question.json endpoint and had English posts working.
But for some reason I can't post one in Spanish. The server's response does not come with an error_text either. (The error_text is sent if English)

The first screenshot shows a successful post in English. The console contains debug statements for the URL we're posting too, the serialized data, SUCCESS/FAIL, and the server's JSON response.

![screen shot 2014-08-20 at 2 23 25 pm](https://cloud.githubusercontent.com/assets/1474048/3986069/07124500-2898-11e4-9bb4-2c1318c808a7.png)

This second one is when we try to post in Spanish:
![screen shot 2014-08-20 at 2 23 59 pm](https://cloud.githubusercontent.com/assets/1474048/3986078/1e22a2d0-2898-11e4-8aa3-7b3c6fe333ff.png)

**Comment by thequbit** [comment]
Was an issue with the Spanish language being loaded within scripts/initializedb.py as 'sp' not 'es'.  This does bring up a good point that better error text should come back if an invalid language code is specified.  This will just remain 'success': false for now though.

Fixed, and closing.
