### ISSUE TITLE
Add a description field to Questions

### ISSUE THREAD

**Issue by Z4P0** [hhroc/yellr#115]
When creating a question there should be a Description field where Admins can add more details to what a question is about

**Comment by thequbit** [comment]
Do you want this apart of the question, or apart of the assignment?  I think the assignment, as you wouldn't want to have a description/meta field for each language, just one in the main language of the admin, right?

**Comment by Z4P0** [comment]
For a better, more complete experience, I think it should be a part of the Question.
If an admin really wants to reach a community they should take the time to speak their language.

If I were purely a Spanish speaker It would feel inconsistent for some question descriptions to appear in English and some in Spanish. While the question text should be enough to get the point across, the description field allows Admins to provide a background on what the Assignment is trying to accomplish

**Comment by thequbit** [comment]
Oooh, I'm with ya.  I get it.  Yup, definitely agree.

-TD

## 

Tim Duffy
http://timduffy.me/
585-210-8353
@arbiterofbits

**Comment by thequbit** [comment]
Added.
