### ISSUE TITLE
Unsure about question_type with assignments

### ISSUE THREAD

**Issue by Z4P0** [hhroc/yellr#118]
When we create a question it has a type:
free_text or multiple_choice

get_assignments returns assignments with question_type: 1

What format are we going with? Either one is fine, or is a combo of the two?
1 = free_text
2 = multiple_choice

**Comment by thequbit** [comment]
get_assignments.json returns 'question_text' and 'question_type'.   'question_text' should be the string type, and the 'question_type' should be the id.  I think I should change it to return at 'question_type_id' and not 'question_text', but instead a description like "Free Text" or "Multiple Choice" so you can put those in a pull down.  This would also require a 'admin/get_question_types.json' end point.  I think we should be doing everything by ID coming back as to limit the number of database calls we need to make.

Thoughts?

**Comment by thequbit** [comment]
Implemented the admin/get_question_types.json.

https://github.com/hhroc/yellr/wiki/API-Documentation#adminget_question_typesjson

Changed the response for get_assignments.json to include question_type_id, not question_type.

**Comment by thequbit** [comment]
Unsure how we will do this on the client side ... for the moment I think we should just hard-code the look up table, and not display anything if it is an unsupported type.

**Comment by Z4P0** [comment]
agreed. just hard the stuff for now, but i got ideas for it. 

save the get_question_types.json response to our localStorage and use that as a reference whenever we render the assignments. should be handy. but we'll implement that later

**Comment by thequbit** [comment]
moved some things around, including including question_type_id rather than question_type, and adding a new end point of admin/get_question_types.json
