### ISSUE TITLE
APP - can't upload images

### ISSUE THREAD

**Issue by Z4P0** [hhroc/yellr#151]
dk what happened. it was working yesterday. what changed?

**Comment by thequbit** [comment]
Are you sure it was working with the merged code base from the server stuff?

Can you diff to see what you changed on the Client side of things?  Do you know if it is a client issue or a server issue?  I can provide extended error_text on failure if you think it would help.

**Comment by Z4P0** [comment]
computers are weird. this is working again after i did a fresh install of the db. didn't change any JS

**Comment by thequbit** [comment]
I'm thinking this has to do with a change in the database structure.

I don't have the correct error checking turned on so testing is easier.
This will be something we clean up today.

## 

Tim Duffy
http://timduffy.me/
585-210-8353
@arbiterofbits
