### ISSUE TITLE
More robust filetype detection

### ISSUE THREAD

**Issue by wywin** [hhroc/yellr#192]
Currently, the filetype detection doesn't appear to be very robust. I selected that I was uploading a photo, forgot what media type I had selected, uploaded an MP3, and it got renamed to .jpg and of course it didn't render. 

Filetype detection should be more robust and support multiple formats per media type.

**Comment by thequbit** [comment]
Great feedback!

Yes, the files are currently saved off with unique id's to disk with an extension based on the media_type field within the HTTP POST to the upload_media.json endpoint.

I will take a look at using the MIME type of the time instead.

**Comment by wywin** [comment]
I am working on implementing this as part of SFD, so hopefully you haven't gotten too far along with your progress. :)

**Comment by thequbit** [comment]
Haven't even started :p.

Looking forward to the pull request!

**Comment by wywin** [comment]
First attempt in #193.

**Comment by thequbit** [comment]
I saw.  I will do my best to take a look before the end of sfd, but no guarantee.  Looks good though!

**Comment by thequbit** [comment]
Merged, tweaked, tested, and accepted into master.  Thanks again @wywin !
