### ISSUE TITLE
Uploaded images coming back with ".processing" as the file extenstion

### ISSUE THREAD

**Issue by Z4P0** [hhroc/yellr#198]
hey Tim, the app is finally uploading and posting images to the server
![screen shot 2014-10-03 at 4 38 14 pm](https://cloud.githubusercontent.com/assets/1474048/4512195/708b82fe-4b3d-11e4-8655-e4787e5bf021.png)

But when you go to the main feed the files have a ".processing" file extension instead of ".jpg"
![screen shot 2014-10-03 at 4 37 27 pm](https://cloud.githubusercontent.com/assets/1474048/4512192/6bce395a-4b3d-11e4-80c5-efe0acd0a650.png)

We use the response from "admin/get_posts" to render this feed. I can write up a quick little hack that would replace that ".processing" with ".jpg" for now

**Comment by thequbit** [comment]
Fixed.  Was issue with merged pull request.
