### ISSUE TITLE
Race condition in image upload?

### ISSUE THREAD

**Issue by thequbit** [hhroc/yellr#199]
When submitting an image on the app, it appears there is a race condition betwen the camera application saving the image and the app being able to upload it.

If you take your time between taking the image, and accepting it then the image appears to upload correctly.

**Comment by Z4P0** [comment]
Hard to say what the best way to tackle this is.

On my phone the race condition doesn't seem to apply. On first run I can take and upload a picture no problem. Same for using the Gallery.

On the phone Bernius lent me, I get the same. On first run I can take and upload a picture. Same for the gallery, although there are some nuances. When selecting from the gallery, the preview image shows but the feedback (that shows the filepath of the image) doesn't. It will still upload tho

**Comment by thequbit** [comment]
I believe we resolved this.  @aztec8 can yo confirm and close?

**Comment by Z4P0** [comment]
confirmed
