### ISSUE TITLE
Can not add image to assignment response

### ISSUE THREAD

**Issue by thequbit** [hhroc/yellr#200]
When responding to an assignment, I can post text, but not attached an image.  It does not launch the same dialog as when i go to upload animage without going through the assignment response flow.

**Comment by Z4P0** [comment]
Was working on this yesterday and it'll need quite a bit of a re-work on the front-end. the JS code is a mess but manageable.

One thing tho, we'll need an extra field added to admin/publish_assignment.json for the assignment_image

My thinking is that there should just be one image for each assignment regardless of the language

**Comment by thequbit** [comment]
This appears to be fixed in latest version of APK.  @aztec8 I will leave it to you close this when you think it has been resolved.

**Comment by thequbit** [comment]
solved.
