### ISSUE TITLE
[MOD] turn on/off auto update

### ISSUE THREAD

**Issue by thequbit** [hhroc/yellr#219]
We should add the ability (check box on the side bar?) to enable/disable auto update of posts coming in.  This would be a great feature to have automatically have posts scrolling by at an event (like tweet deck).

**Comment by Z4P0** [comment]
implemented
![screen shot 2014-10-25 at 1 57 20 pm](https://cloud.githubusercontent.com/assets/1474048/4780611/6df7ca72-5c70-11e4-92f1-a581bfa74d12.png)
