### ISSUE TITLE
Error uploading photo to server

### ISSUE THREAD

**Issue by Z4P0** [hhroc/yellr#23]
Can select a picture from the user's gallery but receive "Error code = 3" when trying to send the file to the server. Both URLs return the same error message (http://yellrdev.wxxi.org/uploadmedia.json and http://yellrdev.wxxi.org/)

**Comment by thequbit** [comment]
@aztec8 I think this is fixed, yes?  Can you close if it is?

**Comment by thequbit** [comment]
closing.  enough has changed that a new ticket should be opened if a similar issue comes up.
