### ISSUE TITLE
Consider changing the token from UUID4 to a secure random string

### ISSUE THREAD

**Issue by dxa4481** [hhroc/yellr#250]
Even though python's implementation of UUID4 uses a secure random number generator to create it's values, there is no gaurentee this will continue to be true. From the UUID spec

http://tools.ietf.org/html/rfc4122#section-6

" Do not assume that UUIDs are hard to guess; they should not be used
   as security capabilities (identifiers whose mere possession grants
   access), for example.  A predictable random number source will
   exacerbate the situation."

**Comment by thequbit** [comment]
First,  great insight.   Second can you post this to hhroc/yellr-server?? 

This report is way out of date.
