### ISSUE TITLE
Time formats

### ISSUE THREAD

**Issue by Z4P0** [hhroc/yellr#5]
Hey Tim, I was wondering how date strings would be passed to the front-end.

It'd be nice to have various ways of showing deadlines: 6 days, 2 weeks, 9 days.
I can write some JS code to handle that kinda stuff just need to know what to expect from the server lol

**Comment by thequbit** [comment]
I usually put them in this format "YYYY-MM-DD HH:MM:SS" and everything gets converted to UTC, however we may want to think about being more uniform with a standard.

Here is the W3 standard that I see a lot:

http://www.w3.org/TR/NOTE-datetime

Example form the link:

```
1994-11-05T08:15:30-05:00
```

-- corresponds to --

```
November 5, 1994, 8:15:30 am, US Eastern Standard Time.
```

Does that make sense?

**Comment by thequbit** [comment]
Feedback from @ryansb we should store in the native DB format, but transport in ISO 8601 (format from above link).  Once we pick a database, we will move forward with the conversion from ISO8601 to whatever it's native format is.  But definitely ISO 8601 for JSON files ( in all directions ).

**Comment by thequbit** [comment]
using datetime.datetime.now() for json transport, and native datetime format for storage in database.
