### ISSUE TITLE
app must generate a unique id (client_id)

### ISSUE THREAD

**Issue by thequbit** [hhroc/yellr#58]
On install, the client should create a save a client_id that is a GUID of sorts, and is unique enough that duplicates aren't an issue.

**Comment by thequbit** [comment]
@aztec8 did you implement this with the GUID JS code we found?

**Comment by Z4P0** [comment]
Yup, got it in no problem

On Wed, Jul 30, 2014 at 5:38 PM, Timothy Duffy notifications@github.com
wrote:

> @aztec8 https://github.com/aztec8 did you implement this with the GUID
> JS code we found?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/hhroc/yellr/issues/58#issuecomment-50683896.

## 

Luis Rosario
@zapo_tec
http://www.luisrosar.io/

**Comment by thequbit** [comment]
Great.  Closing.
