### ISSUE TITLE
Git commits

### ISSUE THREAD

**Issue by Z4P0** [hhroc/yellr#6]
Hey Tim just wanted to let you know what my git commit workflow/schedule is..
- Work on "develop" branch. Push changes to my repo at end of day
- End of week merge into my "master" branch, push to my repo
- Every other week, create pull request to merge into hhroc official repo

I'll push to the hhroc repo next week

**Comment by thequbit** [comment]
That sounds great Luis.  Keep it up!

-TD

On Fri, Jun 6, 2014 at 4:48 PM, luis notifications@github.com wrote:

> Hey Tim just wanted to let you know what my git commit workflow/schedule
> is..
> - Work on "develop" branch. Push changes to my repo at end of day
> - End of week merge into my "master" branch, push to my repo
> - Every other week, create pull request to merge into hhroc official
>   repo
> 
> I'll push to the hhroc repo next week
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/hhroc/yellr/issues/6.

## 

_Tim Duffy_
http://timduffy.me/
(585)-210-8353
@arbiterofbits
