### ISSUE TITLE
Images not posting correctly

### ISSUE THREAD

**Issue by Z4P0** [hhroc/yellr#60]
I was trying to upload images and had this for the form
![screen shot 2014-07-24 at 11 07 21 am](https://cloud.githubusercontent.com/assets/1474048/3689989/f94f70ea-1344-11e4-8053-af16c71edc3d.png)
(I was trying to test if file_name might work)

When I posted it, this is what came back
![screen shot 2014-07-24 at 11 08 49 am](https://cloud.githubusercontent.com/assets/1474048/3690012/14a877f6-1345-11e4-87da-49dfc9f83303.png)
The console.log() shows the form data serialized

When you check the client_logs..
![screen shot 2014-07-24 at 11 06 50 am](https://cloud.githubusercontent.com/assets/1474048/3690035/44f257ba-1345-11e4-8b1e-656baaa2bd9d.png)
the file_name is empty in the details {}

Is the file_name supposed to be empty?..

**Comment by Z4P0** [comment]
No 'Access-Control-Allow-Access' error after pulling the latest changes
![screen shot 2014-07-24 at 1 21 08 pm](https://cloud.githubusercontent.com/assets/1474048/3691894/2085a96a-1357-11e4-8de1-f0f18720e065.png)

![screen shot 2014-07-24 at 1 26 53 pm](https://cloud.githubusercontent.com/assets/1474048/3691956/ba5e181a-1357-11e4-8ea8-7997dd741d6a.png)

**Comment by thequbit** [comment]
Can you paste the output from the pyramid app from the ssh terminal?

On Thu, Jul 24, 2014 at 1:22 PM, luis notifications@github.com wrote:

> No 'Access-Control-Allow-Access' error after pulling the latest changes
> [image: screen shot 2014-07-24 at 1 21 08 pm]
> https://cloud.githubusercontent.com/assets/1474048/3691894/2085a96a-1357-11e4-8de1-f0f18720e065.png
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/hhroc/yellr/issues/60#issuecomment-50049582.

## 

_Tim Duffy_
http://timduffy.me/
(585)-210-8353
@arbiterofbits

**Comment by Z4P0** [comment]
I added a screenshot above. Is that what you mean?

**Comment by thequbit** [comment]
This has manifested into an issue with the ajax call that is doing the HTTP POST with the enctype not being set.  @aztec8 is looking into alternate libraries to perform this task.

**Comment by thequbit** [comment]
Going to open a ticket about the enctype separate from this one, as they are different.
