### ISSUE TITLE
[Errno 98] Address already in use

### ISSUE THREAD

**Issue by Z4P0** [hhroc/yellr#67]
Don't know if I did anything to break this but the server spit out this error today..
![screen shot 2014-07-30 at 11 20 00 am](https://cloud.githubusercontent.com/assets/1474048/3751221/2fd03ade-17fd-11e4-89eb-100b7a5e501f.png)

I did a "git status" and it said everything was up-to-date.
Last night I did "git stash" to get rid of those changes we made

**Comment by decause** [comment]
Usually, this means you already have the yellr server running somewhere, or
another pyramid app serving on port 8080. If not, it would mean that you
are serving on a port that is already claimed, which can be changed in
https://github.com/hhroc/yellr/blob/master/src/server/yellr-serv/development.ini#L31

As it seems you are confident that you didn't accidentally change the port,
I would assume the former case, and not the latter.

On Wed, Jul 30, 2014 at 11:22 AM, luis notifications@github.com wrote:

> Don't know if I did anything to break this but the server spit out this
> error today..
> [image: screen shot 2014-07-30 at 11 20 00 am]
> https://cloud.githubusercontent.com/assets/1474048/3751221/2fd03ade-17fd-11e4-89eb-100b7a5e501f.png
> 
> I did a "git status" and it said everything was up-to-date.
> Last night I did "git stash" to get rid of those changes we made
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/hhroc/yellr/issues/67.

## 

Remy DeCausemaker
Assistant Director
Lab for Technological Literacy
http://foss.rit.edu

Rochester Institute of Technology
Center for Student Innovation
159 Lomb Memorial Drive
Building 87-1680
Rochester, NY 14623

**Comment by thequbit** [comment]
Luis, you probably hit ctrl-z or ctrl-x instead of ctrl-c.

$ ps aux | grep pserv
1000     14853  2.4  0.9 391720 39156 pts/2    Sl+  13:03   0:00
/home/administrator/.virtualenvs/yellr/bin/python
/home/administrator/.virtualenvs/yellr/bin/pserve development.ini
1000     15205  0.0  0.0   9384   904 pts/3    R+   13:04   0:00 grep pserv

$ kill 15205

the you will be all set.  Make sure you do ctrl-c to exit the server.

On Wed, Jul 30, 2014 at 12:51 PM, Remy DeCausemaker <
notifications@github.com> wrote:

> Usually, this means you already have the yellr server running somewhere,
> or
> another pyramid app serving on port 8080. If not, it would mean that you
> are serving on a port that is already claimed, which can be changed in
> 
> https://github.com/hhroc/yellr/blob/master/src/server/yellr-serv/development.ini#L31
> 
> As it seems you are confident that you didn't accidentally change the
> port,
> I would assume the former case, and not the latter.
> 
> On Wed, Jul 30, 2014 at 11:22 AM, luis notifications@github.com wrote:
> 
> > Don't know if I did anything to break this but the server spit out this
> > error today..
> > [image: screen shot 2014-07-30 at 11 20 00 am]
> > <
> > https://cloud.githubusercontent.com/assets/1474048/3751221/2fd03ade-17fd-11e4-89eb-100b7a5e501f.png>
> > 
> > I did a "git status" and it said everything was up-to-date.
> > Last night I did "git stash" to get rid of those changes we made
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/hhroc/yellr/issues/67.
> 
> ## 
> 
> Remy DeCausemaker
> Assistant Director
> Lab for Technological Literacy
> http://foss.rit.edu
> 
> Rochester Institute of Technology
> Center for Student Innovation
> 159 Lomb Memorial Drive
> Building 87-1680
> Rochester, NY 14623
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/hhroc/yellr/issues/67#issuecomment-50644976.

## 

_Tim Duffy_
http://timduffy.me/
(585)-210-8353
@arbiterofbits

**Comment by thequbit** [comment]
Let's use this from now on:

pserve --reload development.ini

Thanks to @decause and @ryansb for this tip!

**Comment by ryansb** [comment]
FYI: `pkill -f pserve` works and is faster.

**Comment by thequbit** [comment]
Awesome!  Thanks @ryansb

On Wed, Jul 30, 2014 at 4:52 PM, Ryan Brown notifications@github.com
wrote:

> FYI: pkill -f pserve works and is faster.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/hhroc/yellr/issues/67#issuecomment-50678104.

## 

_Tim Duffy_
http://timduffy.me/
(585)-210-8353
@arbiterofbits
