### ISSUE TITLE
Create get_user_profile.json

### ISSUE THREAD

**Issue by Z4P0** [hhroc/yellr#82]
Include UUID on request.
Response must include:
- number of submissions
- number of used submissions
- last 5 posts

**Comment by thequbit** [comment]
Implemented at get_profile.json

https://github.com/hhroc/yellr/wiki/API-Documentation#get_profilejson

Note: This does not include 'number of used submissions'.  I still need to figure out how to report a used post.  This might end up being a new table, but I want to think about it first.  I am closing this ticket, and going to create a new one specifically for the used submissions.
