### ISSUE TITLE
Create admin/publish_story.json

### ISSUE THREAD

**Issue by Z4P0** [hhroc/yellr#97]
When an admin approves a submission

**Comment by thequbit** [comment]
I'm thinking this will be a POST and include the following:

title
header_media_object_id
media_object_caption
story_contents

This will keep things simple.  The story_contents blob will be markdown (which allows html).  This will even allow us to embed javascript if we want to get weird ...

We will need to supply some means to get other media objects into the story.  Perhaps a drag/drop kind of thing that generates the html for embedding the media?  This would work well, but I'm concerned there won't be enough real estate on the screen to display the story and all of the possible posts.  

Maybe the flow should be:
1. create collection
2. browse posts
3. add posts to collection
4. 'create story from collection'
5. write story
   (have scrollable list of media objects on right side to drag into the story)
6. publish story

flow item 5 will be a dialog pop-up, but will have the list of posts on the right side that the author can pull from.  Perhaps another pop-up that gives a 'full-screen' display of the image when they click on it, so they can quickly go through the list of posts to see which one they want to include.

You could always save the story as a draft, and then go and add additional posts to the collection so they could be added to the story.

You should also be able to create a story based on an assignment, so you don't have to add all of the posts from an assignment to a collection. (maybe each assignment get's a collection?)

Thoughts?

**Comment by Z4P0** [comment]
Yeah I like that.
I think each assignment should get a collection by default (Maybe each assignment-collection view should be a hub for that assignment where you can view all the submitted responses, and all approved responses).

So we're adding a 'writing platform' to the moderator back-end? Being able to write-up a story, saving drafts, previewing post is gonna get a little involved (not that I'm objecting!). This'll be an important piece.

More so, there should probably be a way to notify a user if their post got used in story. This notification would help 'validate' Yellr to the community. "They really are using content I've submitted".

**Comment by thequbit** [comment]
Yup, we're on the same page.  I think when you go to a collection or an assignment there should be a 'create story' button of sorts.  This opens the pop up where all of the posts from that collection/assignment are in a scrollable list on the right side.  On the left side is a large text box where the post can be written.  There are two 'tabs' on the top (very similar to how github does it) where one is Write and the other is Preview.  The write page would be just that, where you authored the story and write your Markdown/HTML.  The Preview page just uses the Marking.js converter to display what the story will look like.

We will need a 'admin/get_collection_posts.json' or extend admin/get_posts.json to take a collection id.  That will be called to populate the list of posts that the admin can use within the story.

We will also have to create a 'draft' flag in the stories table (and I think I actually need to create the storries table all together ...) to support saving your work.

**Comment by thequbit** [comment]
This has been implemented at admin/publish_story.json.

https://github.com/hhroc/yellr/wiki/API-Documentation#adminpublish_storyjson
